### ISSUE TITLE
Package cl is deprecated

### ISSUE THREAD

**Issue by EternalWill43** [Likhon-baRoy/.emacs.d#2]
First time emacs user here (saw your post on reddit).

I'm on the latest version of Ubuntu, I just installed emacs, and I get this error when I start it up after downloading your config into ~/.emacs.d

> Eager macro-expansion failure: (void-function make-closure)
> package cl is deprecated

**Comment by Likhon-baRoy** [comment]
@EternalWill43 Thanks for issuing the report.
Updated the package management system. Now please try again removing the old configuration.

**Missing fonts** are usually what cause Emacs to fail starting up. So, make sure you have the fonts installed.
 you can connect with me on : Discord `Likhon BaRoy#9576` , [Facebook](https://www.facebook.com/likhonhere007) , [Twitter](https://twitter.com/suidan_lidan) or mail me at `likhonehere007@gmail.com`.
