### ISSUE TITLE
Missing prerequisites

### ISSUE THREAD

**Issue by Reihar** [Likhon-baRoy/.emacs.d#3]
Hi, Thanks for sharing the config. I'm a bit of a long term emacs newbie so please take this report with a grain of salt. I've run tests on Archlinux and macOs, both on emacs-nox. I've also tried it on Windows (with Gui, official build)

It seems there are some missing prerequisites:
* The font Kalpurush seems to be [required](https://github.com/Likhon-baRoy/.emacs.d/blob/main/init.el#L326). My understanding is that you set it as a default for Bengali input but it ends up being necessary to load the config. Maybe a test on available locales could solve this or simply just instructions on how to install the font.
* The font Canterell was not installed on my Windows install and seemed to be required. I could not find any mention of the font in the repository at all. I started from a clean install and I assume it's a package requiring it but I couldn't pinpoint precisely where.
* On both Arch and macOs with the noX version (but not on Windows), [this specific line](https://github.com/Likhon-baRoy/.emacs.d/blob/main/init.el#L406) caused issue. I assume it might be caused by the inability to manipulate the window. So that would make graphical support a prerequisite?

Overall I found that the config is really cool and I'm still trying it out and seeing how to adapt it to my needs. Thanks again and I hope this github issue can help.

**Comment by Likhon-baRoy** [comment]
**Thank you** for your _wonderful inspection_. 
@Reihar  I have made a few updates, if you could test to make sure things are working, that would be great. Please review the README also. And let me know your thoughts on this. :)

**Comment by Reihar** [comment]
Thanks for updating all that! I've had a look and it looks good. Seemed functional after a quick test too.
