### ISSUE TITLE
Wrong copyright holder name

### ISSUE THREAD

**Issue by AkibAzmain** [Likhon-baRoy/.emacs.d#4]
In README,

> Copyright © 2020, 2022, Free Software Foundation, Inc.

Really?

**Comment by AkibAzmain** [comment]
Any thing protected by copyright legally has owner(s).  By default, it's the author of the thing, unless they (the author) assign it to someone else.

Copyright notices are generally written as "Copyright © <years> <author>."  <author> is the author's name (probably legal name) and <years> is the comma separated list of the years and/or year-ranges when the file was written and changed.  For example, a copyright notice can be "Copyright © 1988-1992, 1998, 2020 Someone."  It means that the file was written or changed in 1988, 1989, 1990, 1991, 1992, 1998 and 2020, and the legal rights are holded by "Someone."

I'm pretty sure that this is wrong, though I might be wrong.  You probably meant "Copyright © 2020, 2022, Likhon Baroy." or something like that.

**Comment by Likhon-baRoy** [comment]
Change done 👍🏼 , _(name of the copyright owner)_.
