### ISSUE TITLE
Add Lsp-Mode

### ISSUE THREAD

**Issue by n2ng-dev** [Likhon-baRoy/.emacs.d#5]
hii @Likhon-baRoy 
how to add feature lsp-mode ini this config

thanks

**Comment by xxxlidansuidan** [comment]
```
;; lsp (language server protocal)
(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :config
  (setq lsp-disabled-clients '(emmet-ls)
        lsp-diagnostics-provider :flycheck
        lsp-diagnostics-flycheck-default-level 'warning
        lsp-headerline-breadcrumb-enable nil
        lsp-headerline-breadcrumb-icons-enable nil))

;; fancy in line diagnostics and more
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'at-point)
  :config
  (setq lsp-ui-sideline-enable t
        lsp-ui-sideline-show-hover nil
        lsp-ui-sideline-show-diagnostics t
        lsp-ui-sideline-show-symbol nil
        lsp-ui-sideline-update-mode 'line
        lsp-ui-sideline-delay 0.2
        ))

;; start lsp on various modes
(dolist (mode '(c-mode-hook
                c++-mode-hook
                html-mode-hook
                css-mode-hook
                typescript-mode-hook
                js-mode-hook))
  (add-hook mode (lambda ()
                   (lsp-deferred))))

```As for my PC capability, sometimes **lsp-mode** slow my working process. And that's why I'm using **eglot** instead. 
You can use this snippets in **my-lisp/auto-compilation.el** file, instead of **eglot** place to use **lsp-mode**.

**Comment by Nanank-kho** [comment]
> ```
> ;; lsp (language server protocal)
> (use-package lsp-mode
>   :commands (lsp lsp-deferred)
>   :config
>   (setq lsp-disabled-clients '(emmet-ls)
>         lsp-diagnostics-provider :flycheck
>         lsp-diagnostics-flycheck-default-level 'warning
>         lsp-headerline-breadcrumb-enable nil
>         lsp-headerline-breadcrumb-icons-enable nil))
> 
> ;; fancy in line diagnostics and more
> (use-package lsp-ui
>   :hook (lsp-mode . lsp-ui-mode)
>   :custom
>   (lsp-ui-doc-position 'at-point)
>   :config
>   (setq lsp-ui-sideline-enable t
>         lsp-ui-sideline-show-hover nil
>         lsp-ui-sideline-show-diagnostics t
>         lsp-ui-sideline-show-symbol nil
>         lsp-ui-sideline-update-mode 'line
>         lsp-ui-sideline-delay 0.2
>         ))
> 
> ;; start lsp on various modes
> (dolist (mode '(c-mode-hook
>                 c++-mode-hook
>                 html-mode-hook
>                 css-mode-hook
>                 typescript-mode-hook
>                 js-mode-hook))
>   (add-hook mode (lambda ()
>                    (lsp-deferred))))
> 
> ```As for my PC capability, sometimes **lsp-mode** slow my working process. And that's why I'm using **eglot** instead. 
> You can use this snippets in **my-lisp/auto-compilation.el** file, instead of **eglot** place to use **lsp-mode**. 
> ```

**Comment by n2ng-dev** [comment]
@xxxlidansuidan 
Yes I feel same, lsp-mode slow working
I mean use eglot for lsp, how to add in this config ?

I'm beginner in Flutter developer

thanks

**Comment by Likhon-baRoy** [comment]
```
;; lsp (language server protocal)
(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :config
  (setq lsp-disabled-clients '(emmet-ls)
        lsp-diagnostics-provider :flycheck
        lsp-diagnostics-flycheck-default-level 'warning
        lsp-headerline-breadcrumb-enable nil
        lsp-headerline-breadcrumb-icons-enable nil))

;; fancy in line diagnostics and more
(use-package lsp-ui
  :hook (lsp-mode . lsp-ui-mode)
  :custom
  (lsp-ui-doc-position 'at-point)
  :config
  (setq lsp-ui-sideline-enable t
        lsp-ui-sideline-show-hover nil
        lsp-ui-sideline-show-diagnostics t
        lsp-ui-sideline-show-symbol nil
        lsp-ui-sideline-update-mode 'line
        lsp-ui-sideline-delay 0.2
        ))

;; start lsp on various modes
(dolist (mode '(c-mode-hook
                c++-mode-hook
                html-mode-hook
                css-mode-hook
                typescript-mode-hook
                js-mode-hook))
  (add-hook mode (lambda ()
                   (lsp-deferred))))

```
As for my PC capability, sometimes **lsp-mode** slow down my working process. And that's why I'm using **eglot** instead. 

You can use this snippets in **my-lisp/auto-compilation.el** file.

First open this **auto-compilation.el**  file and there in the end of the file you can see 
```
(use-package eglot
.......)
```
and there instead of **eglot** setting, place upper snippets to use **lsp-mode**.

**Comment by n2ng-dev** [comment]
in **my-lisp/auto-compilation.el** file I was setting like this
`(use-package eglot
  :custom
  (eglot-autoshutdown t)
  (eglot-autoreconnect nil)
  (eglot-confirm-server-initiated-edits nil)
  (eldoc-idle-delay 0.0)
  (eldoc-echo-area-display-truncation-message nil)
  :hook ((c-mode . eglot-ensure)
(dart-mode . eglot.ensure)
         (c++-mode . eglot-ensure))
  :bind (:map eglot-mode-map
              ("C-c r"   . eglot-rename)
              ("C-c C-a" . eglot-code-actions)
              ("C-c C-f" . eglot-format-buffer)
              ("C-c C-i" . eglot-find-implementation))
  :config
  (add-to-list 'eglot-server-programs '(c-mode . ("clangd")))
  (add-to-list 'eglot-server-programs '(c++-mode . ("clangd")))
  (add-to-list 'eglot-server-programs '(python-mode . ("pyls")))
  (add-to-list 'eglot-server-programs '(LaTeX-mode . ("digestif")))
  (add-to-list 'eglot-server-programs '(dart-mode . ("dart_language_server")))
  ;; format on save
  (add-hook 'dart-mode #'(lambda()(add-hook 'before-save-hook 'eglot-format-buffer nil t)))
  (add-hook 'c-mode-hook #'(lambda() (add-hook 'before-save-hook 'eglot-format-buffer nil t)))
  (add-hook 'c++-mode-hook #'(lambda() (add-hook 'before-save-hook 'eglot-format-buffer nil t)))
  (add-hook 'python-mode-hook #'(lambda() (add-hook 'before-save-hook 'eglot-format-buffer nil t))))

(add-hook 'eglot-managed-mode-hook (lambda ()
                                     (add-to-list 'company-backends
                                                  '(company-capf :with company-yasnippet))))
`


in **init.el** file I added this
;```
;; Flutter settings
(use-package dart-mode)
(use-package lsp-dart
  :ensure t
  :hook (dart-mode . eglot-ensure))
(setq lsp-dart-sdk-dir "/Users/nanank_kho/Dev/flutter/bin/cache/dart-sdk")
```

`M-x` just showing eglot-ensure command
![Screenshot 2023-03-03 at 12 33 09](https://user-images.githubusercontent.com/12078569/222640881-7bfb4c23-96dd-4699-a79d-11d4963d87c2.png)

//Error message when open file
![Screenshot 2023-03-03 at 12 40 46](https://user-images.githubusercontent.com/12078569/222640946-d62ff5c5-19ea-4561-a7fe-b087b828a0cc.png)

thanks

**Comment by Likhon-baRoy** [comment]
I don't know the specific server for dart, So, you've to figure it out on your own.
Else everything looks fine and for error messages, it's only _company-mode_ but that's not a problem. It just give this type of error when company doesn't find any compilation backend for the specific file. You don't need to worry about it.
